# Generated by Django 5.2.1 on 2025-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('type', models.CharField(choices=[('M', 'Movie'), ('S', 'Series')])),
                ('poster', models.FileField(blank=True, default='defaults/poster.jpg', null=True, upload_to='posters/')),
                ('url', models.URLField(blank=True, null=True)),
                ('is_watched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
