# Generated by Django 5.1.7 on 2025-07-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=128)),
                ("national_id", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("admin_code", models.CharField(max_length=10)),
                ("permissions_json", models.TextField()),
                ("status", models.CharField(default="active", max_length=20)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=128)),
                ("national_id", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("zipcode", models.CharField(max_length=10)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("loyalty_points", models.IntegerField(default=0)),
                ("status", models.CharField(default="active", max_length=20)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="VendorUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=128)),
                ("national_id", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("shop_name", models.CharField(max_length=150)),
                ("shop_address", models.TextField()),
                ("shop_license_number", models.CharField(max_length=50)),
                ("shop_phone", models.CharField(max_length=20)),
                ("rating", models.FloatField(default=0.0)),
                ("is_verified", models.BooleanField(default=False)),
                ("status", models.CharField(default="active", max_length=20)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
