# Generated by Django 5.2.1 on 2025-07-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='watchitem',
            name='poster',
            field=models.FileField(blank=True, default='defaults/poster.jpg', null=True, upload_to='posters/'),
        ),
    ]
