# Generated by Django 5.2 on 2025-07-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
